### ISSUE TITLE
knora-user mailing list web site not accessible outside Unibas network

### ISSUE THREAD

**Issue by benjamingeer** [dasch-swiss/knora-api#1060]
```
$ curl https://www.maillist.unibas.ch/mailman/listinfo/knora-user
curl: (7) Failed to connect to www.maillist.unibas.ch port 443: Connection refused
```

(Connecting from outside Unibas.)

**Comment by kilchenmann** [comment]
It's only accessible from the University network. Use the VPN. Otherwise you should ask the it-service of the university: https://its.unibas.ch/content.cfm?nav=260&content=68

**Comment by benjamingeer** [comment]
But then how do the people at Lausanne access it?

**Comment by kilchenmann** [comment]
Yes, that's a good question. The mailing list service from the university isn't that flexible. Perhaps we should search for a better solution. 
What is the advantage of the university mailing list? Or can we create our own? I don't know.

**Comment by subotic** [comment]
> But then how do the people at Lausanne access it?

Via email? Sending an email to subscribe works from everywhere.

**Comment by subotic** [comment]
We have a few channels: github, mailinglist, slack, IRC, and direct email. We just never published the channels publicly, which we probably should.

**Comment by benjamingeer** [comment]
> Via email? Sending an email to subscribe works from everywhere.

Then we have to tell them where to send it. The Knora README.md says:

> Please use the [knora-user](https://www.maillist.unibas.ch/mailman/listinfo/knora-user) mailing list for technical questions.

But if you click on that link and you're not on the Unibas VPN, it doesn't work.

**Comment by subotic** [comment]
Then we should write something like this:

> Please use the knora-user mailing list for technical questions. To subscribe send an email with `subscribe` to [knora-users@unibas.ch](mailto:knora-user@maillist.unibas.ch)

**Comment by subotic** [comment]
But I don't know if it would be better to find another "home" for our mailing list. Without access to the mailing list page, there is no way to search the archive.

**Comment by loicjaouen** [comment]
sorry for the late answer:
- we subscribed to the mailing list and receive e-mails
- we don't access it otherwise than by looking in our mail history
