### ISSUE TITLE
Implement upload of PDF and text files in API v2

### ISSUE THREAD

**Issue by benjamingeer** [dasch-swiss/knora-api#1202]
Lausanne specifically need CSV files (temporarily at least, before converting the data in them to RDF).

Needs https://github.com/dhlab-basel/Sipi/issues/283.
Needs https://github.com/dhlab-basel/Sipi/issues/299.
Needs https://github.com/dhlab-basel/Sipi/issues/301.
Needs https://github.com/dhlab-basel/Sipi/issues/302.

**Comment by gfoo** [comment]
do you think to have time to release pdf support in the next Knora release of April or May?

**Comment by benjamingeer** [comment]
I don't know, because this depends on when Lukas feels well enough to work on Sipi.
