### ISSUE TITLE
ark in salsah v1.5

### ISSUE THREAD

**Issue by loicjaouen** [dasch-swiss/knora-api#1313]
Most projects need a permanent ID, we want to add the ark to salsah v1.5, which is the tool they use right now.

But salsah v1.5 call api v1 which doesn't return an ark id.

What option do you think is the best:
- compute ark from iri? ... I don't like it because it depends on config in knora that we would need to either query or duplicate
- make salsah to issue a second call to v2 to get the ark`
- add ark in the v1 answer?

**Comment by benjamingeer** [comment]
The second option would be the easiest for me. :)

But the third one wouldn't be difficult, either.

**Comment by loicjaouen** [comment]
because the second is for me to implement ;)

I should also be able to code the third one (but you will be faster)

Which one makes more sense?

**Comment by benjamingeer** [comment]
The third one makes more sense because it will mean fewer requests. Would you like to try it as an exercise? You basically just need to call `resourceIri.toSmartIri.fromResourceIriToArkUrl()`, then figure out how to add that to the JSON returned in v1.

Otherwise, I can do it next week.

**Comment by loicjaouen** [comment]
resolved by #1486
