### ISSUE TITLE
Try Apache Jena Fuseki again

### ISSUE THREAD

**Issue by benjamingeer** [dasch-swiss/knora-api#1374]

**Comment by benjamingeer** [comment]
Trying with Tomcat 9.

The directory `/etc/fuseki` must exist, and Tomcat must have write access to it.

To use Tomcat's management webapp, this needs to be added to `/conf/tomcat-users.xml`:

```xml
<role rolename="manager-gui"/>
<user username="admin" password="root" roles="manager-gui"/>
```

**Comment by benjamingeer** [comment]
In the database config files like `knora-test.ttl`, the object of `tdb:location` has to be an absolute path.

**Comment by subotic** [comment]
You should try to run it inside Docker. There are a few Docker images available.
