### ISSUE TITLE
Missing definition "TimeValue" in knora-base

### ISSUE THREAD

**Issue by lrosenth** [dasch-swiss/knora-api#1397]
Thereis no "TimeValue" in knora-base in order to store a timestamp as "normal" value of a resource.

Needs https://github.com/dhlab-basel/Knora-ui/issues/307.
Needs https://github.com/dhlab-basel/knora-py/issues/12.
Needs https://github.com/dhlab-basel/knora-api-js-lib/issues/41.

**Comment by benjamingeer** [comment]
Do you have a use case in mind?

**Comment by subotic** [comment]
It is defined in the old Salsah and there are projects that use it.
