### ISSUE TITLE
Can't build jekyll docs on macOS Mojave

### ISSUE THREAD

**Issue by benjamingeer** [dasch-swiss/knora-api#1437]
I installed Jekyll following the instructions here:

https://jekyllrb.com/docs/installation/macos/

I had to install Ruby using Homebrew as described there, because Mojave's built-in Ruby is too old for Jekyll.

`docs/makeSite` then complained about many gems it couldn't find. I installed each of these manually.

Now if I use the existing Gemfile.lock, it complains:

```
[error] /usr/local/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:319:in `check_for_activated_spec!':
You have already activated public_suffix 4.0.1, but your Gemfile requires public_suffix 3.0.3.
```

If I `rm Gemfile.lock` and regenerate it using `bundle install`, `docs/makeSite` complains:

```
[error] /Users/benjamingeer/.gem/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/runtime.rb:319:in `check_for_activated_spec!':
You have already activated i18n 1.6.0, but your Gemfile requires i18n 0.9.5.
```

**Comment by subotic** [comment]
yes, compiling the docs locally with jekyll is always making problems. That is why, for https://github.com/dasch-swiss/dsp-docs we are using MkDocs.

**Comment by benjamingeer** [comment]
MkDocs loos like it’s the same thing as Jekyll, except that it’s written in Python instead of Ruby... Is the idea that Python handles library dependencies better than Ruby?

**Comment by subotic** [comment]
Yes, managing python dependencies is much easier (for me at least). Also, we use Python in other contexts. Messing with the whole Ruby installation just for docs generation is a bit of an overkill.
