### ISSUE TITLE
JSON-LD Serialization of an xsd:dateTimeStamp

### ISSUE THREAD

**Issue by tobiasschweizer** [dasch-swiss/knora-api#1439]
I think I spotted an inconsistency in how an `xsd:dateTimeStamp` is serialized in JSON-LD:

https://github.com/dhlab-basel/Knora/blob/fb7adba749bf6b37ed36f49f2d6cb3f553b92382/webapi/src/test/resources/test-data/ontologyR2RV2/minimalOntologyWithValueObjects.jsonld#L25

vs.

https://github.com/dhlab-basel/Knora/blob/fb7adba749bf6b37ed36f49f2d6cb3f553b92382/webapi/src/test/resources/test-data/resourcesR2RV2/Testding.jsonld#L343-L346

Shouldn't this be serialized as an object in both cases?

Needs https://github.com/dhlab-basel/Knora-ui/issues/324.
Needs https://github.com/dhlab-basel/knora-py/issues/11.
Needs https://github.com/dhlab-basel/knora-api-js-lib/issues/47.

**Comment by benjamingeer** [comment]
You’re right, it should be an object it both cases.

**Comment by tobiasschweizer** [comment]
Changing `knora-api:lastModificationDate` for the ontologies v2  routes in JSON-LD will require changes in  https://github.com/dhlab-basel/knora-py, https://github.com/dhlab-basel/knora-ui and https://github.com/dhlab-basel/knora-api-js-lib
