### ISSUE TITLE
Add route to retrieve knora-api version

### ISSUE THREAD

**Issue by LukasStoeckli** [dasch-swiss/knora-api#1444]

**Comment by benjamingeer** [comment]
Already exists: https://docs.knora.org/paradox/03-apis/api-v2/reading-and-searching-resources.html#get-a-full-representation-of-a-version-of-a-resource-by-iri

Or did you mean something else?

**Comment by LukasStoeckli** [comment]
yes, this has the sole purpose of retrieving the version of knora (that is included in the response now, but the goal is to have it separated)

**Comment by benjamingeer** [comment]
OK! There's some documentation here on how to write a route:

https://docs.knora.org/paradox/05-internals/design/api-v2/how-to-add-a-route.html

If anything isn't clear, please ask, and also please suggest anything you think should be added to that documentation.

**Comment by LukasStoeckli** [comment]
thanks
