### ISSUE TITLE
Improve performance of repository upgrade

### ISSUE THREAD

**Issue by benjamingeer** [dasch-swiss/knora-api#1451]
Following the discussion in https://discuss.dasch.swiss/t/release-day-and-rollback/103/6, we're going to try improving the performance of automated repository upgrades by implementing a new upgrade framework in C++. Work is starting in https://github.com/dhlab-basel/knora-update.

**Comment by benjamingeer** [comment]
The [Raptor](http://librdf.org/raptor/) C library for RDF parses a 35 MB TriG file dump of the `knora-test` repository in 31 minutes. The [RDF4J](https://rdf4j.eclipse.org) Java library for RDF parses the same file in 2 seconds. I'm going to do this in Scala.

@lrosenth

**Comment by benjamingeer** [comment]
Parsing in C++ (compiled with clang with `-O3`):

```
$ time cmake-build-release/knora-update 'file:///Users/benjamingeer/git/knora-update/test/test-data/knora-test.trig'
cmake-build-release/knora-update: parsed RDF into model

real	31m39.584s
user	31m22.038s
sys	0m3.426s
```

Parsing in Scala:

```
> webapi / runMain org.knora.webapi.util.TransformData /Users/benjamingeer/git/knora-update/test/test-data/knora-test.trig
[info] Compiling 1 Scala source to /Users/benjamingeer/git/Knora/webapi/target/scala-2.12/classes ...
[info] Done compiling.
[info] Packaging /Users/benjamingeer/git/Knora/webapi/target/scala-2.12/webapi_2.12-9.1.0-2-g46b2fd0-SNAPSHOT.jar ...
[info] Done packaging.
[info] Running (fork) org.knora.webapi.util.TransformData /Users/benjamingeer/git/knora-update/test/test-data/knora-test.trig
[info] Parsed 320998 statements in 2184 ms
```

**Comment by benjamingeer** [comment]
Made branch `wip/1451-repository-update` to do this in Scala.

**Comment by lrosenth** [comment]
:-)


Am 01.10.2019 um 12:41 schrieb Benjamin Geer <notifications@github.com<mailto:notifications@github.com>>:


The Raptor<http://librdf.org/raptor/> C library for RDF parses a 35 MB TriG file dump of the knora-test repository in 31 minutes. The RDF4J<https://rdf4j.eclipse.org/> Java library for RDF parses the same file in 2 seconds. I'm going to do this in Scala.

@lrosenth<https://github.com/lrosenth>
