### ISSUE TITLE
Carriage return in resource label

### ISSUE THREAD

**Issue by gfoo** [dasch-swiss/knora-api#1462]
Don't know if you should accept or not carriage return char `\r` in labels? (actually, you're not accept it while `\n` is accepted):
```json
{
  "@type" : "anything:Thing",
  "knora-api:attachedToProject" : {
    "@id" : "http://rdfh.ch/projects/0001"
  },
  "rdfs:label": "Transcription ; Les bons historiens sont les meilleurs precepteurs d'une nation\r\n",
  "@context" : {
    "rdf" : "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
    "knora-api" : "http://api.knora.org/ontology/knora-api/v2#",
    "rdfs" : "http://www.w3.org/2000/01/rdf-schema#",
    "xsd" : "http://www.w3.org/2001/XMLSchema#",
    "anything" : "http://0.0.0.0:3333/ontology/0001/anything/v2#"
  }
}
```
Error:
```json
{
    "knora-api:error": "org.knora.webapi.BadRequestException: Invalid http://www.w3.org/2000/01/rdf-schema#label: Transcription ; Les bons historiens sont les meilleurs precepteurs d'une nation\r\n",
    "@context": {
        "knora-api": "http://api.knora.org/ontology/knora-api/v2#"
    }
}
```

Do I have to cleanup my string labels inputs?

**Comment by benjamingeer** [comment]
@tobiasschweizer If I remember correctly, we had to reject `\r` (in `StringFormatter.toSparqlEncodedString()`) because we used that character internally as a word separator so that the Lucene full-text search index would find words that are separated by markup but not by whitespace. But looking at the code, it seems that we now use `INFORMATION SEPARATOR TWO (U+001E)` for this. So is there any reason to reject `\r`?

**Comment by tobiasschweizer** [comment]
>  If I remember correctly, we had to reject \r (in StringFormatter.toSparqlEncodedString()) because we used that character internally as a word separator so that the Lucene full-text search index would find words that are separated by markup but not by whitespace.

If you have two parts in a text marked up as paragraphs and remove the markup, they wouldn't necessarily be separated in the string representation, so we add `INFORMATION SEPARATOR TWO (U+001E)`. But this does not depend on an actual newline, it is a setting in the mapping: `separatesWords`, https://docs.knora.org/paradox/03-apis/api-v1/xml-to-standoff-mapping.html#basic-structure-of-a-mapping 

Wasn't the reason to reject `\r` the differences in line endings between Unix and Windows that we do not want to end up in the tripelstore?

**Comment by benjamingeer** [comment]
> Wasn't the reason to reject `\r` the differences in line endings between Unix and Windows that we do not want to end up in the tripelstore?

Maybe. If so, I think it still makes sense.

@gfoo 

> Do I have to cleanup my string labels inputs?

Would it really be useful to have `\n` in a label? It won't be displayed correctly in a browser anyway, it will just appear as a space.

**Comment by gfoo** [comment]
yep, not usefull. This character is really confusing anyway. I cleaned my input data,  no problems there, you can close.

n.b. : the main use case is when Windows' users copy/paste data containing `\r` chars, but it is the role of the UI to clean data I think.
