### ISSUE TITLE
[Salsah 1.5] A `projectAdmin` is not allowed to create a `knora-base:Region`

### ISSUE THREAD

**Issue by mrivoal** [dasch-swiss/knora-api#1468]
When trying to create a `knora-base:Region` for a `Dingbild` in `Anything` project, I get the following error:
```
{"status":3,"error":"org.knora.webapi.ForbiddenException: User http://rdfh.ch/users/AnythingAdminUser does not have permissions to create a resource in project http://rdfh.ch/projects/0001","access":"NO_ACCESS"}
```
The bug can be reproduced by logging in as `anything.admin` user. 
With `anything.user01`, there is no bug though: this user can create a `Region` without problem.

I am using Knora v. 9.1.0-4-gac6c1f5

**Comment by subotic** [comment]
Also, if it is an existing resource, which one is it (the IRI)?

**Comment by mrivoal** [comment]
I created a `Dingbild` of my own. 

As for the loading script, I don't know. I will ask @loicjaouen. However, I spotted this bug on another ontology for which a schema permission that was working in knora v6.0 doesn't seem to work anymore under knora v.9.

**Comment by subotic** [comment]
Ok, thanks for reporting. I will see if I can reproduce it next week.

**Comment by mrivoal** [comment]
@subotic, do you know when you plan to have a look at this?

**Comment by subotic** [comment]
I will take a look at it today.

**Comment by subotic** [comment]
Hmm, so with the latest version (v10.0.0-3-gc5ecdc2) I'm able to create a region on a "Dingbild" resource in the "Anything" project logged in as "Anything Admin":

<img width="1447" alt="Screenshot 2019-10-27 16 42 51" src="https://user-images.githubusercontent.com/400790/67637278-24c51c00-f8d9-11e9-827a-115ff1225bb6.png">

**Comment by mrivoal** [comment]
OK. It must have been a bug in the v9. I will check when we upgrade to v10.
