### ISSUE TITLE
Limit Gravsearch query to a single data named graph

### ISSUE THREAD

**Issue by benjamingeer** [dasch-swiss/knora-api#1474]
From https://discuss.dasch.swiss/t/gravsearch-limit-to-one-named-graph/110:

Allow a Gravsearch query to include one or more `FROM` clauses. These will then be included in the generated SPARQL prequery, along with a `FROM` clause for each built-in graph (built-in Knora ontologies and data) and each project-specific ontology.

@loicjaouen

**Comment by loicjaouen** [comment]
Maybe we should drop this feature request: empirically, on all the recent queries we ran, limiting to one graph (`FROM <graph_iri>`) slowed down their execution.

**Comment by benjamingeer** [comment]
OK, thanks for trying it. Please feel free to reopen this issue later if you change your mind.
