### ISSUE TITLE
Admin client code generation

### ISSUE THREAD

**Issue by tobiasschweizer** [dasch-swiss/knora-api#1476]
A `StoredUser` has the following definition (https://github.com/dasch-swiss/knora-api-js-lib/blob/master/src/models/admin/stored-user.ts):

```
/**
 * Represents a Knora user.
 */
@JsonObject("StoredUser")
export class StoredUser extends User {

    /**
     * The ID of the enclosing object.
     */
    @JsonProperty("id", String)
    id: string = "";

}
```

The expected payload for `updateUserBasicInformation` looks like this (https://github.com/dasch-swiss/knora-api-js-lib/blob/master/test/data/api/admin/users/update-user-request.json):

```
{
    "username": "donald.big.duck",
    "email": "donald.big.duck@example.org",
    "givenName": "Big Donald",
    "familyName": "Duckmann",
    "lang": "de"
}
```

Because `StoredUser` is a subclass of `User`, it has more properties than present in the expected payload.

**Comment by tobiasschweizer** [comment]
There is a problem when attempting to convert `test/data/api/admin/users/get-user-project-memberships-response.json` to a `ProjectsResponse`:

```
ERROR: Error: Error: Fatal error in JsonConvert. Failed to map the JSON object to the class "ProjectsResponse" because of a type error.

	Class property: 
		projects

	Expected type: 
		[ReadProject]

	JSON property: 
		projects

	JSON type: 
		[object,object,object]

	JSON value: 
		[{"description":[{"value":"A demo project of a collection of images","language":"en"}],"id":"http://rdfh.ch/projects/00FF","keywords":["collection","images"],"logo":null,"longname":"Image Collection Demo","ontologies":["http://www.knora.org/ontology/00FF/images"],"selfjoin":false,"shortcode":"00FF","shortname":"images","status":true},{"description":[{"value":"<p>Das interdisziplinäre Forschungsprojekt \"<b><em>Die Bilderfolgen der Basler Frühdrucke: Spätmittelalterliche Didaxe als Bild-Text-Lektüre</em></b>\" verbindet eine umfassende kunstwissenschaftliche Analyse der Bezüge zwischen den Bildern und Texten in den illustrierten Basler Inkunabeln mit der Digitalisierung der Bestände der Universitätsbibliothek und der Entwicklung einer elektronischen Edition in der Form einer neuartigen Web-0.2-Applikation.\n</p>\n<p>Das Projekt wird durchgeführt vom <a href=\"http://kunsthist.unibas.ch\">Kunsthistorischen Seminar</a> der Universität Basel (Prof. B. Schellewald) und dem <a href=\"http://www.dhlab.unibas.ch\">Digital Humanities Lab</a> der Universität Basel (PD Dr. L. Rosenthaler).\n</p>\n<p>\nDas Kernstück der digitalen Edition besteht aus rund zwanzig reich bebilderten Frühdrucken aus vier verschiedenen Basler Offizinen. Viele davon sind bereits vor 1500 in mehreren Ausgaben erschienen, einige fast gleichzeitig auf Deutsch und Lateinisch. Es handelt sich um eine ausserordentlich vielfältige Produktion; neben dem Heilsspiegel finden sich ein Roman, die Melusine,  die Reisebeschreibungen des Jean de Mandeville, einige Gebets- und Erbauungsbüchlein, theologische Schriften, Fastenpredigten, die Leben der Heiligen Fridolin und Meinrad, das berühmte Narrenschiff  sowie die Exempelsammlung des Ritters vom Thurn.\n</p>\nDie Internetpublikation macht das digitalisierte Korpus dieser Frühdrucke  durch die Möglichkeiten nichtlinearer Verknüpfung und Kommentierung der Bilder und Texte, für die wissenschaftliche Edition sowie für die Erforschung der Bilder und Texte nutzbar machen. Auch können bereits bestehende und entstehende Online-Editionen damit verknüpft  werden , wodurch die Nutzung von Datenbanken anderer Institutionen im Hinblick auf unser Corpus optimiert wird.\n</p>"}],"id":"http://rdfh.ch/projects/0803","keywords":["Basel","Basler Frühdrucke","Bilderfolgen","Contectualisation of images","Inkunabel","Kunsthistorisches Seminar Universität Basel","Late Middle Ages","Letterpress Printing","Narrenschiff","Sebastian Brant","Wiegendrucke","early print","incunabula","ship of fools"],"logo":"incunabula_logo.png","longname":"Bilderfolgen Basler Frühdrucke","ontologies":["http://www.knora.org/ontology/0803/incunabula"],"selfjoin":false,"shortcode":"0803","shortname":"incunabula","status":true},{"description":[{"value":"Anything Project"}],"id":"http://rdfh.ch/projects/0001","keywords":[],"logo":null,"longname":"Anything Project","ontologies":["http://www.knora.org/ontology/0001/anything","http://www.knora.org/ontology/0001/something"],"selfjoin":false,"shortcode":"0001","shortname":"anything","status":true}]

Fatal error in JsonConvert. Failed to map the JSON object to the class "ReadProject" because the defined JSON property "members" does not exist:

	Class property: 
		members

	JSON property: 
		members

```

**Comment by tobiasschweizer** [comment]
Groups endpoint `createGroup`: `CreateGroupRequest` is not compatible with `test/data/api/admin/groups/create-group-request.json`

**Comment by tobiasschweizer** [comment]
@benjamingeer maybe https://github.com/dasch-swiss/knora-api-js-lib/pull/72#issuecomment-543070413 is helpful

**Comment by benjamingeer** [comment]
Can you try #1478?

> Because `StoredUser` is a subclass of `User`, it has more properties than present in the expected payload.

I added a `BasicUserInfo` class to deal with this.

> the defined JSON property "members" does not exist

This is a property with cardinality `MayHaveMany` (`0-n`). I changed the TypeScript class generation so that properties like that are optional. Please see if that fixes the problem.

> Groups endpoint

Could you please provide details of what is incorrect? Or tell me how I can test this myself?

**Comment by benjamingeer** [comment]
> @benjamingeer maybe https://github.com/dasch-swiss/knora-api-js-lib/pull/72#issuecomment-543070413 is helpful

It's too vague. I need to know exactly which properties are missing, etc.

**Comment by tobiasschweizer** [comment]
> It's too vague. I need to know exactly which properties are missing, etc.

Ok, I will provide more details then. I will try #1478 first to see if this fixes some of the problems.

I will also document how to integrate the generate admin code sou you will be able to do this yourself in the future.

**Comment by tobiasschweizer** [comment]
@benjamingeer Please try the following:

- get `http://0.0.0.0:3333/clientapi/typescript`
- clone <https://github.com/dasch-swiss/knora-api-js> and switch to branch `wip/71-release-1.0.0`
- from the project root of `knora-api-js`, run `npm install`
- from the project root of `knora-api-js`, run `./integrate-generated-files-admin.sh <path-to-generated-Knora-Admin-API-code>`
- from the project root of `knora-api-js`, run `npm test` (should work, otherwise your changes broke something that worked before)
- in `/Users/tobi/gitreps/knora-api-js-lib/src/api/admin/users/users-endpoint.spec.ts` search for `xit` and change them to `it` (activate deactivated tests)
-  run `npm test` to see if they pass now

**Comment by tobiasschweizer** [comment]
> It's too vague. I need to know exactly which properties are missing, etc.

The test framework will indicate the properties that cause the problems:

`users-endpoint.spec.ts`: 

- ` xit("should update user information" ...` -> changing to `it` shows the payload problems

`groups-endpoint.spec`:

- `xit("should create a group" ...` -> see above
- `xit("should update a group" ...` -> see above
- `xit("should update a group" ...` -> see above

**Comment by benjamingeer** [comment]
I fixed the problem with the users endpoint.

In the groups endpoint tests, I don't understand the error messages:

```
FAILED TESTS:
  GroupsEndpoint
    Method createGroup
      ✖ should create a group
        HeadlessChrome 77.0.3865 (Mac OS X 10.14.6)
      Error: Expected object to have properties
          description: 'NewGroupDescription'
          project: 'http://rdfh.ch/projects/00FF'
      Expected object not to have properties
          projectIri: 'http://rdfh.ch/projects/00FF'
          at <Jasmine>
          at UserContext.<anonymous> (src/api/admin/groups/groups-endpoint.spec.ts:85:36 <- src/api/admin/groups/groups-endpoint.spec.js:113:48)
          at <Jasmine>

    Method updateGroup
      ✖ should update a group
        HeadlessChrome 77.0.3865 (Mac OS X 10.14.6)
      Error: Expected object not to have properties
          selfjoin: false
          id: 'http://rdfh.ch/groups/00FF/images-reviewer'
          at <Jasmine>
          at UserContext.<anonymous> (src/api/admin/groups/groups-endpoint.spec.ts:153:36 <- src/api/admin/groups/groups-endpoint.spec.js:179:48)
          at <Jasmine>

    Method updateGroupStatus
      ✖ should update a group
        HeadlessChrome 77.0.3865 (Mac OS X 10.14.6)
      Error: Expected object not to have properties
          name: ''
          selfjoin: false
          id: 'http://rdfh.ch/groups/00FF/images-reviewer'
          at <Jasmine>
          at UserContext.<anonymous> (src/api/admin/groups/groups-endpoint.spec.ts:191:36 <- src/api/admin/groups/groups-endpoint.spec.js:215:48)
          at <Jasmine>
```

"Expected object to have properties" and "Expected object not to have properties" are not clear to me. Which object is it talking about? What does it expect the object to look like?

**Comment by tobiasschweizer** [comment]
@benjamingeer I am looking at it now.

**Comment by tobiasschweizer** [comment]
Thanks for working on this! 

Regarding the problems in `GroupsEndpoint`:

1. "Method createGroup": 

   - `CreateGroupRequest` has the non optional members: `name`,  `projectIri`, `selfjoin`, `status`
   -  `test/data/api/admin/groups/create-group-request.json` has members: `name`, `description`, `project`, `status`, `selfjoin`
   ->  `description` is not present on `CreateGroupRequest`, `projectIri` and `project` are different but should be called the same. This is how I understand 

> Error: Expected object to have properties
          description: 'NewGroupDescription'
          project: 'http://rdfh.ch/projects/00FF'
      Expected object not to have properties
          projectIri: 'http://rdfh.ch/projects/00FF'

The spec simply compares `CreateGroupRequest` to `test/data/api/admin/groups/create-group-request.json`

2. "Method updateGroup":

    - `StoredGroup` has the non optional members: `id`, `name`, `selfjoin` and optional members `description` and `status`
    - `test/data/api/admin/groups/update-group-request.json` has members: `name`, `description`
    -> `selfjoin` and `id` are not present on `test/data/api/admin/groups/update-group-request.json`,  but they are on `StoredGroup`


3. "Method updateGroupStatus"

   - `StoredGroup` has the non optional members: `id`, `name`, `selfjoin` and optional members `description` and `status`
   - "test/data/api/admin/groups/change-group-status-request.json" has only one member `status`
   -> `id`, `name`, `selfjoin` are not in  "test/data/api/admin/groups/change-group-status-request.json"

**Comment by tobiasschweizer** [comment]
@benjamingeer I will now carry on with the specs for projects endpoint. 

If you need more details on groups specs, please let me know. I am also available on FaceTime if necessary

**Comment by benjamingeer** [comment]
Looking at the code, I don't see how `request.data()` is actually the `CreateGroupRequest`. The `request` variable is created here:

```typescript
const request = jasmine.Ajax.requests.mostRecent();
```

But I don't know what `mostRecent()` is.

What is `NewGroupDescription`? Where is it defined?

And the error message is ambiguous. When I read `Expected object to have properties`, I don't know whether the `object` is `request` or `payload`.

I think it would be clearer to have an error message saying something like: "Expected request to be { ... }, but it is { ... }".

**Comment by benjamingeer** [comment]
OK now I see that `NewGroupDescription` is in the test data. At first I got confused because "Expected object to have properties" sounds like it means "The object has no properties, and I expected it to have some properties." And "Expected object not to have properties" sounds like it means "The object has some properties, and I expected it to have no properties." Now I see what it means.

**Comment by tobiasschweizer** [comment]
> But I don't know what mostRecent() is.

This is the AJAX request performed by the method that was called in the test, see https://github.com/jasmine/jasmine-ajax.

> And the error message is ambiguous. When I read Expected object to have properties, I don't know whether the object is request or payload.

I think it is the payload.

**Comment by tobiasschweizer** [comment]
It just compares the payload of the AJAX request to the properties present on the JSON test data. Maybe some options can be configured to get better error messages, but I have to check the docs first for this.

**Comment by tobiasschweizer** [comment]
`projects-endpoint.spec.ts`:

- "Method updateProject": "id" and "shortcode" are not present in test JSON payload "test/data/api/admin/projects/update-project-request.json" but on `StoredProject`

**Comment by tobiasschweizer** [comment]
@benjamingeer Ok, I managed to write the tests for projects endpoint, there is just one tests that is ignored, see https://github.com/dasch-swiss/knora-api/issues/1476#issuecomment-544406192

I will now proceed with the docs for the release.

**Comment by benjamingeer** [comment]
OK I fixed the bugs so that all the tests pass. The changes in Knora are in https://github.com/dasch-swiss/knora-api/pull/1478.
