### ISSUE TITLE
InconsistentTriplestoreDataException on get resource ?version=TIMESTAMP

### ISSUE THREAD

**Issue by gfoo** [dasch-swiss/knora-api#1500]
I get the following error:
```json
{"knora-api:error":"org.knora.webapi.InconsistentTriplestoreDataException: Subject http://rdfh.ch/0001/uMkv9Q1rQUyW0XtE0kdvAA/values/7YHUfGGhQBeY7jaOCiKZFQ does not have predicate http://www.knora.org/ontology/knora-base#deleteComment","@context":{"knora-api":"http://api.knora.org/ontology/knora-api/v2#"}}
```
when I try to get a specific version of a resource  which has a deleted property without a delete comment.

1. create a resource with a property value
2. delete property value
3. get the resource with version=resource creation date

Script to reproduce: [timestamp-error.zip](https://github.com/dasch-swiss/knora-api/files/3792829/timestamp-error.zip)

 (of course if I add a `deleteComment` when I delete the property, I don't have this error)

**Comment by benjamingeer** [comment]
Thanks, that’s a bug, will fix.
