### ISSUE TITLE
Error importing data into GraphDB with curl

### ISSUE THREAD

**Issue by subotic** [dasch-swiss/knora-api#1512]
Steps:

 1. Load data into GraphDB and 
 2. Run upgrade script

Error:
```
com.ontotext.trree.consistency.ConsistencyException: Consistency check empty_string_0 failed:
http://rdfh.ch/0807/21BTn-EJRpSFteiiOvApbg/values/V_m80QSURbOwKg2O6vzRyw http://www.knora.org/ontology/knora-base#valueHasString ""^^<http://www.w3.org/2001/XMLSchema#string>
```

Since there is no `knora-base#valueHasString` property on the resource before the upgrade, I guess it was added during upgrade.

@benjamingeer I will send you a link per email, where you can download the data.

**Comment by subotic** [comment]
When you implement the fix, could you please base your branch on b4ce837dbfd4a21b6f65013af7274565c8a0c224, so that we can then release `v10.0.1`. Afterward, you can merge it into `develop`.

**Comment by benjamingeer** [comment]
This seems to be a bug in GraphDB's parsing of the TriG input file. The input data contains a newline, not an empty string. If we import it via the GraphDB workbench, it works, but if we use curl, it doesn't.

**Comment by benjamingeer** [comment]
Ontotext are looking into this. For now, the workaround is to use the [Manual Upgrade](https://docs.knora.org/paradox/04-publishing-deployment/updates.html#manual-upgrade) procedure, and to upload the transformed data to GraphDB using the GraphDB workbench instead of `upload-repository.sh`.

**Comment by benjamingeer** [comment]
Ontotext have kindly informed us that curl strips newlines from an upload when you use the `-d/--data` option (!) and you have to use `--data-binary` instead.

**Comment by subotic** [comment]
great, thanks!
