### ISSUE TITLE
Updating the name of a list

### ISSUE THREAD

**Issue by benjamingeer** [dasch-swiss/knora-api#1520]
`CreateListApiRequestADM` includes `name`, but `ChangeListInfoApiRequestADM` does not, is this correct?

**Comment by subotic** [comment]
The `name` property is a bit under discussion. It is useful in import scripts if unique, but not really to useful IMO in the GUI.

**Comment by benjamingeer** [comment]
The client API is supposed to be the same in all target languages, so the code generation doesn't support the idea of a property that would exist in only one target language.

**Comment by benjamingeer** [comment]
It would also simplify the classes that need to be generated if the create request and the update request could be subclasses of a common base class.

**Comment by benjamingeer** [comment]
Otherwise, there is more work to be done in the code generation algorithm to support this case (an update request that has an ID but no base class).
