### ISSUE TITLE
Makefile not running the right tests

### ISSUE THREAD

**Issue by benjamingeer** [dasch-swiss/knora-api#1525]
I’ve just realised that `ResourcesRouteV2E2ESpec` fails if I run it locally with the develop branch. It fails (correctly) because of changes I made in this PR, which was merged two weeks ago:

https://github.com/dasch-swiss/knora-api/pull/1505

However, we never got any failures for it in Travis or GitHub CI, because it was never run. Looking at the Travis test runs that were done for that PR when it was merged, as well as the latest GitHub CI run for the develop branch, you can see that most of the E2E tests are skipped during the "E2E tests" job:

https://github.com/dasch-swiss/knora-api/runs/300674005

https://github.com/dasch-swiss/knora-api/runs/311653127

I think the problem is in the Makefile:

https://github.com/dasch-swiss/knora-api/blob/develop/Makefile#L260

This line seems to be excluding the E2E tests when it should be running the E2E tests. I think this means that tagged E2E tests have not been run on Travis/GitHub since this PR was merged, which introduced that Makefile:

https://github.com/dasch-swiss/knora-api/pull/1459

(I also now see that I forgot to tag E2E tests, so they've still been run.)

**Comment by subotic** [comment]
Hmm, good catch. Thanks!
