### ISSUE TITLE
Redundant list routes?

### ISSUE THREAD

**Issue by benjamingeer** [dasch-swiss/knora-api#1528]
I think these two routes are the same:

* `PUT /admin/lists/IRI` https://github.com/dasch-swiss/knora-api/blob/develop/webapi/src/main/scala/org/knora/webapi/routing/admin/ListsRouteADM.scala#L141
* `PUT /admin/lists/infos/IRI` https://github.com/dasch-swiss/knora-api/blob/develop/webapi/src/main/scala/org/knora/webapi/routing/admin/ListsRouteADM.scala#L235

Is that correct? If so, the client API only needs to implement one of them.

**Comment by subotic** [comment]
Thanks for reporting!

@LukasStoeckli is kindly taking over the work on lists.  There is an open  PR https://github.com/dasch-swiss/knora-api/pull/1447 and there it looks like the redundancy is not present anymore. But he will surely check to be sure.

**Comment by benjamingeer** [comment]
OK. It looks like the existing requests and responses in the lists route are changing in #1447, so I will pause work on #1509 until #1447 is merged.
