### ISSUE TITLE
If a default object access permission is set on both a group and on a resource class, the wrong permission is applied

### ISSUE THREAD

**Issue by mrivoal** [dasch-swiss/knora-api#1533]
With the current version of `develop`, if you define both :
- `DefaultObjectAccessPermission` for ProjectAdmin group as `"CR knora-admin:Creator|M knora-admin:ProjectMember|V knora-admin:KnownUser|RV knora-admin:UnknownUser"`
- and a more restricted DefaultObjectAccessPermission for a resource class (here, `anything:YellowThing`) such as `"CR knora-admin:ProjectAdmin|M knora-admin:ProjectMember|V knora-admin:KnownUser"`
Then the DefaultObjectAccessPermission on the group will apply for any instance of a `anything:YellowThing` that you create.

If you log in as `anything.admin@example.org` in Salsah 1.5 and try to create a `anything:YellowThing`, you will see that the DefaultObjectAccessPermission attached to the resource will be `"CR knora-admin:Creator|M knora-admin:ProjectMember|V knora-admin:KnownUser|RV knora-admin:UnknownUser"` .

**Comment by subotic** [comment]
This is actually correct behavior according to the permission precedence rules described here: https://docs.knora.org/paradox/05-internals/design/api-admin/administration.html#permission-precedence-rules

The permissions defined for the `ProjectAdmin` group take precedence over the permissions defined for the resource class.

**Comment by subotic** [comment]
Whether the defined permission precedence rules make sense is another question, which we can gladly discuss.

**Comment by mrivoal** [comment]
All right. I thought this was a bug, sorry. Thanks for having a look.

I will check my use case and see if I manage somehow to set up the permissions for this project like I want. If so, there is no need to discuss the precedence rules.

**Comment by mrivoal** [comment]
If I don't define a `DefaultObjectAccessPermission` for `ProjectAdmin` group (which is not really needed as members of this group are also `ProjectMember` and the `DefaultObjectAccessPermission` for `ProjectMember` group apply to them), then the  `DefaultObjectAccessPermission` of the resource class is applied as expected.

I'm closing this issue.
