### ISSUE TITLE
Use ForbiddenResource consistently

### ISSUE THREAD

**Issue by benjamingeer** [dasch-swiss/knora-api#1543]
If you request two resources from `/v2/resources`, and you only have permission to see one of them, you should get one resource and one `ForbiddenResource`.

Also, #1521 changed Gravsearch so that if you don't have permission to see a dependent resource, you get a link value with just the target resource's IRI. This is also what `/v2/resources` does. It would be more consistent to use `ForbiddenResource` for the dependent resource, too.

**Comment by benjamingeer** [comment]
I think this should be done in `ConstructResponseUtilV2.splitMainResourcesAndValueRdfData`. In the function `nestResources`, there's this comment:

https://github.com/dasch-swiss/knora-api/blob/develop/webapi/src/main/scala/org/knora/webapi/util/ConstructResponseUtilV2.scala#L564


```
// If we don't have the dependent resource, that means that the user doesn't have
// permission to see it, or it's been marked as deleted. Just return the link
// value without a nested resource.
```

So I think `splitMainResourcesAndValueRdfData` needs to be able to distinguish between a resource that was marked as deleted and resource that the user doesn't have permission to see. If the resource was marked as deleted, we can still return the link value. If the user doesn't have permission to see the resource, we can return `ForbiddenResource` as the dependent resource.

**Comment by benjamingeer** [comment]
@tobiasschweizer Would you be able to think with me a bit about how to do this? (See https://github.com/dasch-swiss/knora-api/issues/1543#issuecomment-570210243.)

**Comment by tobiasschweizer** [comment]
yes, maybe on Friday?

**Comment by benjamingeer** [comment]
OK great, thanks.

**Comment by tobiasschweizer** [comment]
FaceTime at 11h?

**Comment by benjamingeer** [comment]
Yes!

**Comment by benjamingeer** [comment]
After talking with @tobiasschweizer, it looks like this can be done by creating a collection here of IRIs of resources that are filtered out because of permissions:

https://github.com/dasch-swiss/knora-api/blob/develop/webapi/src/main/scala/org/knora/webapi/util/ConstructResponseUtilV2.scala#L320

That collection can then be used in `nestResources()`:

https://github.com/dasch-swiss/knora-api/blob/develop/webapi/src/main/scala/org/knora/webapi/util/ConstructResponseUtilV2.scala#L567

It will be necessary to pass `ForbiddenResource` through the call stack.

**Comment by benjamingeer** [comment]
Following discussion in https://discuss.dasch.swiss/t/how-to-deal-with-forbidden-resources-and-values-consistently/153, it seems preferable to remove `ForbiddenResource`.
