### ISSUE TITLE
Incorrect property names in generated admin API code

### ISSUE THREAD

**Issue by tobiasschweizer** [dasch-swiss/knora-api#1545]
On current develop (https://github.com/dasch-swiss/knora-api/commit/064ca4a4381c79acbd9b33e3ee847e46ecc6d443), I integrated the generated code for admin and the v2 test data.

The admin API has changed (breaking):

- `CreateGroupRequest`: `groupDescription` -> inconsistent with `groups/create-group-request.json`
- `UpdateGroupRequest`: `groupDescription` -> inconsistent with `groups/update-group-request.json`
- `UpdateProjectRequest`: `projectDescription` -> inconsistent with `projects/update-project-request.json`

There are also changes in v2 test date, but I haven't spotted structural changes.

**Comment by tobiasschweizer** [comment]
@subotic I think we need to automate the integration of generated code and test data in knora-api-lib-js.

**Comment by benjamingeer** [comment]
Do you mean that on develop, the generated test data is inconsistent with the generated classes? Or inconsistent with the classes you had before?

**Comment by benjamingeer** [comment]
The admin API hasn't changed as far as I know.

**Comment by tobiasschweizer** [comment]
> Do you mean that on develop, the generated test data is inconsistent with the generated classes? 

Yes.

```
/**
 * A request to create a group.
 */
@JsonObject("CreateGroupRequest")
export class CreateGroupRequest {

    /**
     * A description of a user group
     */
    @JsonProperty("groupDescription", String, true)
    groupDescription?: string = undefined;
``` 

in the generated test data:

```
{
    "name": "NewGroup",
    "description": "NewGroupDescription",
    "project": "http://rdfh.ch/projects/00FF",
    "status": true,
    "selfjoin": false
}
```

There are two problems: the tests did not compile because `description` is now called `groupDescription`. But even after fixing this `groupDescription` is inconsistent with the JSON test data.

**Comment by tobiasschweizer** [comment]
> The admin API hasn't changed as far as I know.

Probably it is just the declarations for the client code that have changed, not even the data.

**Comment by benjamingeer** [comment]
I'm pretty sure this is a code generation bug introduced in #1526. Will fix.

**Comment by tobiasschweizer** [comment]
That would be great. But I think we should automate the integration of generated data and run the tests with each merge into develop.
