### ISSUE TITLE
Generate client code and run Tests in knora-api-js-lib automatically

### ISSUE THREAD

**Issue by tobiasschweizer** [dasch-swiss/knora-api#1554]
Knora should automatically check for its compatibility with https://github.com/dasch-swiss/knora-api-js-lib.

Necessary steps:
- start Knora stack (load test data, restart api ...)
- generate client code and save to tmp location: 
    - `curl -o ts.zip http://localhost:3333/clientapi/typescript`
    - `tar -C ts -xf ts.zip`
- clone https://github.com/dasch-swiss/knora-api-js-lib
- integrate admin code and data and v2 test data:
    - `npm run integrate-admin-code <path-to-generated-code>`
    - `npm run integrate-v2-test-data <path-to-generated-code>`
    - `npm run expand-jsonld-test-data`
- run tests: https://github.com/dasch-swiss/knora-api-js-lib/blob/df166a773a58833f6ab1d3630b3405608d8c5107/.travis.yml#L38-L51 

needs https://github.com/dasch-swiss/knora-api-js-lib/pull/115 (should be ready to merge soon)

**Comment by subotic** [comment]
We could add a make target, which would execute all these steps.
