### ISSUE TITLE
[Salsah 1.5] If an error is thrown when a user clicks on "save" button for a resource, he can't save his data 

### ISSUE THREAD

**Issue by mrivoal** [dasch-swiss/knora-api#1557]
If any error is thrown when a user clicks on "save" button for a resource (e.g. his data entry doesn't comply with cardinality), even he fixes his mistake, he won't be able to save his data because clicking a second time on "save" button will not trigger any action.

He will have to cancel the whole entry (by clicking on "cancel" button) and re-entry his data again.

**Comment by loicjaouen** [comment]
on #1515 I missed a case where the submit action fails and I don't re-set the listen action for the submit button... investigating
