### ISSUE TITLE
Admin lists: createChildNode should send a httpPost request, not httpPut

### ISSUE THREAD

**Issue by flavens** [dasch-swiss/knora-api#1559]
In the method `createChildNode()` in the generated code of knora-api-js-lib, the API request is wrong: it is not `httpPut()` but `httpPost()`.

method to update:
```typescript
createChildNode(node: CreateChildNodeRequest): Observable<ApiResponseData<ListInfoResponse> | ApiResponseError> {
        return this.httpPut(.... ..... ....);
}
```

reference to #1509

**Comment by benjamingeer** [comment]
Thank you for catching this! Please try PR #1560.
