### ISSUE TITLE
Change signature of client method to update user's system admin membership

### ISSUE THREAD

**Issue by kilchenmann** [dasch-swiss/knora-api#1579]
Can someone explain me, why we have to use the type `StoredUser` in users endpoint `updateUserSystemAdminMembership` (https://github.com/dasch-swiss/knora-api-js-lib/blob/324b84f4b1b63b6770f7d6dfa70c8f5c7b8c4088/src/api/admin/users/users-endpoint.ts#L274-L286)? 

```typescript
/**
 * Updates a user's SystemAdmin membership.
 * 
 * @param user The user to be updated.
 */
updateUserSystemAdminMembership(user: StoredUser): Observable<ApiResponseData<UserResponse> | ApiResponseError> {

    return this.httpPut("/iri/" + encodeURIComponent(user.id) + "/SystemAdmin", { systemAdmin: user.systemAdmin }).pipe(
        map(ajaxResponse => ApiResponseData.fromAjaxResponse(ajaxResponse, UserResponse, this.jsonConvert)),
        catchError(error => this.handleError(error))
    );

}
```
<br>

Almost of the time we are working with type `ReadUser` (all the responses are of this type). `ReadUser` expands the `StoredUser` which expands the `User` type. It doesn't seem to be easy to reduce the user information we are working with (from `ReadUser` to `StoredUser`). For me it doesn't make sense. It would be better if the `updateUserSystemAdminMembership` could look as follow:

```typescript
updateUserSystemAdminMembership(userIri: string, systemAdmin: boolean): Observable<ApiResponseData<UserResponse> | ApiResponseError> {
...
}
```

**Comment by benjamingeer** [comment]
`StoredUser` is intended to avoid circular imports in TypeScript. This is explained here:

https://docs.knora.org/paradox/05-internals/design/client-api/index.html#generated-classes

**Comment by kilchenmann** [comment]
In this case I have to reduce the user data of type `ReadUser` to this `StoredUser`?
What are the arguments against the proposal: `updateUserSystemAdminMembership(userIri: string, systemAdmin: boolean)`?

**Comment by benjamingeer** [comment]
> What are the arguments against the proposal

None at all, I'll add this. :)

**Comment by kilchenmann** [comment]
That would be great. Thank you @benjamingeer
