### ISSUE TITLE
Improve error message with more details about the failure

### ISSUE THREAD

**Issue by flavens** [dasch-swiss/knora-api#1580]
**Issue description**
The full text search has been tested on Knora-app after checking out Knora-api develop branch with the latest commit. The data has been reloaded with `make init-db-test`. The search failed with some terms like "suisse" and "france". An error 404 has been thrown (see screen shot below).

**What must have happened** 
I forgot to move the server file of BEOL into the images folder of BEOL.
In the BEOL mappings, a default XSL transformation is specified. This is a file hosted by Sipi which Knora requested but Sipi could not serve because it did not find it.

**What we would like**
A better explained error message would have been helpful to understand the situation.
Knora makes an internal request to Sipi for the XSLT file. If this request fails, Knora's error message should say that it tried to get this file from Sipi but got an unsuccessful response.

**Screen shots**
Error in the console of Chrome:
<img width="2560" alt="Screenshot 2020-01-23 at 15 14 37" src="https://user-images.githubusercontent.com/29532462/72992486-1614d500-3df4-11ea-88b7-7d536617d2cd.png">

**Comment by benjamingeer** [comment]
Thanks, I'll do this, it's easy to fix.
