### ISSUE TITLE
Allow upload of PDFs to SIPI

### ISSUE THREAD

**Issue by gfoo** [dasch-swiss/knora-api#1581]
Is there any rules for Sipi upload route to accept or not a PDF?

I've an error for example with this file:  [Programme_Colloque_Bertrand.pdf](https://github.com/dasch-swiss/sipi/files/3944634/Programme_Colloque_Bertrand.pdf)

Using the binary, the PDF sounds ok:
```
$ docker run --rm -v $(pwd):/image daschswiss/knora-sipi:v10.1.1 -f "/image/Programme_Colloque_Bertrand.pdf" out-sipi.pdf
pdf has 2 pages
```

But using the upload route (the call is stuck):
```
curl -s -X POST -F filename=@Programme_Colloque_Bertrand.pdf http://localhost:1024/upload?token=xxxx
```

**Comment by subotic** [comment]
I've moved the issue to the `knora-api` repo.

**Comment by benjamingeer** [comment]
> I've moved the issue to the knora-api repo.

@subotic Why? I thought this issue was about getting Sipi to validate PDF files.

**Comment by subotic** [comment]
Isn't it about a problem with uploading PDFs? Since this logic is implemented in a `lua` script, it could probably be solved in this repo.

**Comment by benjamingeer** [comment]
Which logic? The Lua script just calls Sipi’s C++ functions to process the file. If Sipi can’t parse a particular PDF file, there’s nothing the Lua script can do about it.

**Comment by lrosenth** [comment]
OK, I had a look at it. It requires at leastsome major changes in

- knora-api/sipi/scripts/upload.lua
- knora-api/sipi/scripts/store.lua

Currently all upload files are being converted to a sipi image object and then converted to a JPEG2000 file. In order to cope with PDF's (and also .ttl's, .xnml's etc.) we have to build in a switch which checks the MIME type and performs

- the conversion as it used to be if the input MIME-type is of TIFF, PNG,JPEG,J2K etc.
- just copies the file to the proper place (tmp and then the images/project/...)

To rememer, PDF's that are in the images-folder can be served

1. as PDF-download (complete PDF) if the URL looks like this

**Comment by benjamingeer** [comment]
> Currently all upload files are being converted to a sipi image object and then converted to a JPEG2000 file.

No, `upload.lua` checks whether the file is an image. If not, it doesn't do any conversion:

https://github.com/dasch-swiss/knora-api/blob/develop/sipi/scripts/upload.lua#L116

**Comment by benjamingeer** [comment]
Support for uploading PDF files was added in https://github.com/dasch-swiss/knora-api/pull/1206.

**Comment by benjamingeer** [comment]
These changes were also announced on Discuss DaSCH:

https://discuss.dasch.swiss/t/support-non-image-files-in-knora-api-v2/33/2

**Comment by gfoo** [comment]
@benjamingeer did you try to reproduce the bug? `curl -s -X POST -F filename=@Programme_Colloque_Bertrand.pdf http://localhost:1024/upload?token=xxxx` I found this bug on 10 Dec 2019

**Comment by benjamingeer** [comment]
@gfoo I haven't tried to reproduce it, but if it works with one PDF file and not with another PDF file, I think the problem has to be in the C++ code in Sipi.

**Comment by mrivoal** [comment]
@lrosenth (or to whom it may concern) any news regarding this issue? We still have a lot of things to fix to be able to release Lumieres.Lausanne but if we can't import PDFs, then we can't release anything.

**Comment by benjamingeer** [comment]
I've reproduced this and can confirm that it depends on the content of the PDF file. Moved to https://github.com/dasch-swiss/sipi/issues/319.

**Comment by gfoo** [comment]
@benjamingeer thanks for the test
