### ISSUE TITLE
virtual "knora-api" problems

### ISSUE THREAD

**Issue by lrosenth** [dasch-swiss/knora-api#1593]
I encountered same problems with the virtual `knora-api`- ontology which does not conform to the OWL standard.

- rdfs:label my not be subclass of a restriction class to assign cardinality. See [here](http://protege-project.136.n4.nabble.com/Why-it-is-not-possible-to-have-cardinality-restriction-for-rdfs-label-or-rdfs-comment-td4658506.html). A solution might be - as mentioned - by adding a declaration of rdfs:label as a data property
- Datatype restriction should probably not use "subClassOf" but "rdfs:range":
```
knora-api:Date a rdfs:Datatype;
  rdfs:comment "Represents a date as a period with different possible precisions.";
  rdfs:label "Date literal";
  rdfs:range [ a rdfs:Datatype;
      owl:onDatatype xsd:string;
      owl:withRestrictions [
          xsd:pattern "(GREGORIAN|JULIAN):\\d{1,4}(-\\d{1,2}(-\\d{1,2})?)?( BC| AD| BCE| CE)?(:\\d{1,4}(-\\d{1,2}(-\\d{1,2})?)?( BC| AD| BCE| CE)?)?"
        ]
    ] .
```

Eventually we should follow OWL-standards in order to use tools to visualize ontologies and SPARQL queries using knora-api:

**Comment by benjamingeer** [comment]
> rdfs:label my not be subclass of a restriction class to assign cardinality.

OK.

> Datatype restriction should probably not use "subClassOf" but "rdfs:range":

Why?

The definition of `rdfs:range` says that its subject has to be an instance of `rdf:Property`:

https://www.w3.org/TR/rdf-schema/#ch_range

**Comment by lrosenth** [comment]
For the label the statement
```
rdfs:label a owl:DatatypeProperty .
```
seems to solve the problem. Then, rdfs:label my get a cardinality.

**Comment by lrosenth** [comment]
>>Datatype restriction should probably not use "subClassOf" but "rdfs:range":
Why?
 There seems to be a problem with RDF/OWL parsers. Error messages... So the ontology cannot be read by protege and others I tried out...

**Comment by benjamingeer** [comment]
OK, it looks like the recommended way to do this is with `owl:onDatatype`:

https://books.google.fr/books?id=tYb6AQAAQBAJ&pg=PA119&lpg=PA119&dq=%22owl:onDatatype%22+%22owl:withRestrictions%22&source=bl&ots=T4lZIqoL92&sig=ACfU3U3lC5exWCHil7s7h54SWbgIAAoM6Q&hl=en&sa=X&ved=2ahUKEwj76ZObgMDnAhUJXxoKHTbZAUEQ6AEwBnoECAgQAQ#v=onepage&q=%22owl%3AonDatatype%22%20%22owl%3AwithRestrictions%22&f=false

**Comment by lrosenth** [comment]
Oh... I have first to understand this :-) It's been a long time...

**Comment by lrosenth** [comment]
OK, I think (?!) I got it.
Previous code with errors:
```
knora-api:Color a rdfs:Datatype;
  rdfs:comment "Represents a color.";
  rdfs:label "Color literal";
  rdfs:subClassOf [ a rdfs:Datatype;
      owl:onDatatype xsd:string;
      owl:withRestrictions [
          xsd:pattern "#([0-9a-fA-F]{3}){1,2}"
        ]
    ] .
```

becomes (which protege swallows without errors):
```
knora-api:Color a rdfs:Datatype;
  rdfs:comment "Represents a color.";
  rdfs:label "Color literal";
  owl:onDatatype xsd:string;
  owl:withRestrictions [ xsd:pattern "#([0-9a-fA-F]{3}){1,2}" ] .
```
@benjamingeer You think that's correct?

**Comment by lrosenth** [comment]
It seems that the following version does work – but is has it the same "semantics" as the original...? I hope so...

[knora-api.ttl.zip](https://github.com/dasch-swiss/knora-api/files/4172323/knora-api.ttl.zip)

**Comment by benjamingeer** [comment]
Thanks, I'll change this.
