### ISSUE TITLE
Obtaining UUID on Value Creation

### ISSUE THREAD

**Issue by tobiasschweizer** [dasch-swiss/knora-api#1595]
Is there a way to obtain a new value's UUID in the response to the value creation? 

I would like to read a new value back from Knora right after its creation . But in order to do that, I need its UUID. The only other possibility I can think of is making a full resource request but this is not ideal.

**Comment by tobiasschweizer** [comment]
The docs state

> The response is a JSON-LD document containing only @id and @type, returning the IRI and type of the value that was created.

I guess it would be enough to add the value's UUID to the response.

**Comment by benjamingeer** [comment]
> I guess it would be enough to add the value's UUID to the response.

Good idea, and easy to implement, too.

**Comment by tobiasschweizer** [comment]
great :-)

I would suggest to return the UUID also in case of the creation of a new value.

**Comment by benjamingeer** [comment]
> I would suggest to return the UUID also in case of the creation of a new value.

Isn’t that what you asked for above? Or did you mean something different?

**Comment by tobiasschweizer** [comment]
No, my question was about the creation of a new value.

**Comment by tobiasschweizer** [comment]
sorry, my mistake

**Comment by tobiasschweizer** [comment]
see edited https://github.com/dasch-swiss/knora-api/issues/1595#issuecomment-584200184

**Comment by benjamingeer** [comment]
The UUID doesn’t change when a new version of a value is created. That’s why we have the UUID.

**Comment by tobiasschweizer** [comment]
I know. It is just convenience.

**Comment by benjamingeer** [comment]
OK no problem.

**Comment by tobiasschweizer** [comment]
> The UUID doesn’t change when a new version of a value is created. That’s why we have the UUID.

I was about to create an issue for this last week but then I realized that I already had the UUID ...
