### ISSUE TITLE
Make client tests not depend on incunabula

### ISSUE THREAD

**Issue by benjamingeer** [dasch-swiss/knora-api#1600]
@tobiasschweizer Ivan asked me if we could remove the dependency on the Incunabula test data from the test requests/responses that are generated for `knora-api-js-lib`. I found only two things that depend on Incunabula:

- The test data for the search route uses `SharedTestDataADM.gravsearchComplexRegionsForPage`.
- The test for the `getProjectKeywordsTestResponse` function in the projects endpoint gets the keywords for the Incunabula project.

Can I change these so they use the `anything` test data instead?

**Comment by tobiasschweizer** [comment]
Yes, absolutely. Do you want to create a related PR in knora-api-js-lib yourself (adapt import of test data and adaption of specs) or do you need some help with that?
