### ISSUE TITLE
Cannot find `knora-base:valueHasComment` in the documentation

### ISSUE THREAD

**Issue by mrivoal** [dasch-swiss/knora-api#1606]
By reviewing knora-app mock-up, I just came across a value property that I didn't know existed and that I can't find in the documentation. It is `knora-base:valueHasComment`. 

I also wonder what is the purpose and the use expected for this comment, and how dependant is this property of the value. 
For instance, if a user A create a value, can a user B post a comment on this value? Can a user C delete the comment?

**Comment by benjamingeer** [comment]
You're right, this should be documented but it isn't. It could be used to add an explanation of why the value was created or modified.

To add a comment to an existing value, you have to make a new version of the value, so you need modify permission on the value.

**Comment by benjamingeer** [comment]
To change or remove a comment, you also need modify permission on the value.

**Comment by mrivoal** [comment]
Great. Thank you for the explanation.

**Comment by SepidehAlassi** [comment]
`knora-api:valueHasComment` has been added to the api documentation, please see the part about [creating a new value](https://docs.knora.org/03-apis/api-v2/editing-values/)
