### ISSUE TITLE
typos in admin doc

### ISSUE THREAD

**Issue by loicjaouen** [dasch-swiss/knora-api#1620]
incidentally browsing admin docs that fails to render nicely:
https://docs.knora.org/paradox/03-apis/api-admin/projects.html

![Capture d’écran 2020-03-02 à 10 34 35](https://user-images.githubusercontent.com/3933654/75663634-727bd780-5c71-11ea-90d6-e8c4652ca1e6.png)

**Comment by SepidehAlassi** [comment]
resolved in PR #1656
