### ISSUE TITLE
ontology's last modification date

### ISSUE THREAD

**Issue by loicjaouen** [dasch-swiss/knora-api#1622]
Dear all,
how do I find about an ontology's last modification date?
Documentation `paradox/03-apis/api-v2/ontology-information.html#ontology-updates` states:
```
When changing an existing ontology, the client must always supply the ontology’s knora-api:lastModificationDate, which is returned in the response to each update.
```

I thought I had the answer and was about to update the documentation to add that this information was to be found by requesting the `http://host/v2/ontologies/metadata` (at the top of that section). But it is actually not there for all ontologies:

`GET https://knora.unil.ch/v2/ontologies/metadata`
```json
{
  "@graph": [
    {
      "@id": "http://api.knora.org/ontology/knora-admin/v2",
      "@type": "owl:Ontology",
      "knora-api:attachedToProject": {
        "@id": "http://www.knora.org/ontology/knora-admin#SystemProject"
      },
      "knora-api:isBuiltIn": true,
      "rdfs:label": "The Knora admin ontology"
    },
    {
      "@id": "http://knora.unil.ch/ontology/0001/anything/v2",
      "@type": "owl:Ontology",
      "knora-api:attachedToProject": {
        "@id": "http://rdfh.ch/projects/0001"
      },
      "knora-api:lastModificationDate": "2017-12-19T15:23:42.166Z",
      "rdfs:label": "The anything ontology"
    },
    {
      "@id": "http://knora.unil.ch/ontology/0101/parole-religieuse/v2",
      "@type": "owl:Ontology",
      "knora-api:attachedToProject": {
        "@id": "http://rdfh.ch/projects/0101"
      },
      "rdfs:label": "Religious speech embarrassed, radio debates and controversies around gender : Switzerland and France , 2006-2016"
    },
   [...]
  ```

So where is that last modification date to be found?

Best regards and sorry for the carnival :(

**Comment by loicjaouen** [comment]
if it helps making my point intelligible, above is the PR I started even if it does not solve the case

**Comment by benjamingeer** [comment]
Built-in ontologies don't have a last modification date, because you can't change them.

If you write an ontology by hand in Turtle (instead of using the Knora API to create it), then you have to include a last modification date yourself.

**Comment by loicjaouen** [comment]
thanks @benjamingeer 

And I guess that the recommended way to get it (once set) is the project's metadata route?

`GET https://{{host}}/v2/ontologies/metadata/{{project_encoded_iri}}`

```json
{
  "@id": "http://api.test.dasch.swiss/ontology/0001/anything/v2",
  "@type": "owl:Ontology",
  "knora-api:attachedToProject": {
    "@id": "http://rdfh.ch/projects/0001"
  },
  "knora-api:lastModificationDate": "2017-12-19T15:23:42.166Z",
  "rdfs:label": "The anything ontology",
  "@context": {
    "knora-api": "http://api.knora.org/ontology/knora-api/v2#",
    "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
    "owl": "http://www.w3.org/2002/07/owl#"
  }
}
```

**Comment by benjamingeer** [comment]
You can get it that way, or by requesting the ontology itself:

https://docs.knora.org/paradox/03-apis/api-v2/ontology-information.html#querying-an-ontology

You would probably want to do this anyway if you were going to edit the ontology.
