### ISSUE TITLE
outdated documentation of clientAPIRoute?

### ISSUE THREAD

**Issue by SepidehAlassi** [dasch-swiss/knora-api#1647]
Having a  look at the code, the documentation for [Generating Client API code](https://docs.knora.org/paradox/05-internals/development/generating-client-apis.html) seems to be outdated. 

- The route is not `clientapi` anymore, it is `clientapitest`

- the route does not accept a target parameter, such as `typescript`, as explained in the documentation.
 
Is there anything I am missing, or the documentation needs to be simply updated? If so, I can do that.

**Comment by benjamingeer** [comment]
The documentation source is up to date, but the generated documentation on docs.knora.org hasn't been regenerated for some time. It used to be possible to do this with `make docs-publish`, but I'm trying it now and it just hangs.

Also, I think we're not supposed to make GitHub issues anymore, we're supposed to make user stories on YouTrack now. Could you make one for regenerating the docs on docs.knora.org, and ask Ivan to help?

**Comment by SepidehAlassi** [comment]
Since it was a question (labeled so) rather than an issue/bug, I thought I ask it here. Now that I am sure there is work to be done, I will make a user story for it.

**Comment by SepidehAlassi** [comment]
> The documentation source is up to date, but the generated documentation on docs.knora.org hasn't been regenerated for some time. It used to be possible to do this with `make docs-publish`, but I'm trying it now and it just hangs.
> 
> Also, I think we're not supposed to make GitHub issues anymore, we're supposed to make user stories on YouTrack now. Could you make one for regenerating the docs on docs.knora.org, and ask Ivan to help?

Since it was a question (labeled so) rather than an issue/bug, I thought I ask it here. Now that I am sure there is work to be done, I will make a user story for it.
