### ISSUE TITLE
admin API: get all groups fails

### ISSUE THREAD

**Issue by lrosenth** [dasch-swiss/knora-api#1687]
A call to "http://0.0.0.0:3333/admin/groups" (in browser, postman, whatever) which should return all groups fails with an error:

```json
{
    "error": "org.knora.webapi.exceptions.TriplestoreResponseException: Couldn't parse Turtle from triplestore"
}
```
Running this on latest develop branch of knora-api

**Comment by benjamingeer** [comment]
I can't reproduce this. For me it returns the two groups in the Knora test data.

**Comment by benjamingeer** [comment]
How did you create the data in your repository? Can we try it with your data?

**Comment by SepidehAlassi** [comment]
dear Lukas, 

I could not regenerate the issue. I just tried both POST and GET requests as below, I don't get any issue. (On develop branch)

**GET:**

![Screenshot 2020-08-12 at 08 00 05](https://user-images.githubusercontent.com/8567642/89980322-f353ec00-dc71-11ea-8e9e-d2f890971bd3.png)

**POST:** (to create a group)
![Screenshot 2020-08-12 at 08 31 28](https://user-images.githubusercontent.com/8567642/89982668-75deaa80-dc76-11ea-9178-ca7edd93144e.png)

Can you please give more info: which triplestore you use, and also the log of API? And as @benjamingeer said, can we try with your data?

**Comment by lrosenth** [comment]
Strange, I

- downloaded a new knora-api from github
the branch is:
```bash
rosenth@MacBook-Pro knora-api % git branch
* develop
```
- I did "make build"
- then "make init-db-test"
- then "make stack-up"
If I then enter the  url in the browser or postman: ```http://0.0.0.0:3333/admin/groups```and I get the error.

Strange...

**Comment by lrosenth** [comment]
I will reinstall everything - may be this helps :-)

**Comment by benjamingeer** [comment]
What happens if you do `make test`?

**Comment by lrosenth** [comment]
After  a complete reinstall it seems to work right now – strange, but good ;-)
No idea what happened - either the reinstall went wrong, or something else (my opiates???)
Thanks @benjamingeer and @SepidehAlassi

**Comment by benjamingeer** [comment]
No problem, let us know if it happens again.

**Comment by SepidehAlassi** [comment]
> Strange, I
> 
> * downloaded a new knora-api from github
>   the branch is:
> 
> ```shell
> rosenth@MacBook-Pro knora-api % git branch
> * develop
> ```
> 
> * I did "make build"
> * then "make init-db-test"
> * then "make stack-up"
>   If I then enter the  url in the browser or postman: `http://0.0.0.0:3333/admin/groups`and I get the error.
> 
> Strange...

@lrosenth to have everything cleanly installed, you have to first do `make stack-down-delete-volumes`. So basically the only steps you need to do is:
1. `make stack-down-delete-volumes`
2. `make init-db-test`
3. `make stack-up`
