### ISSUE TITLE
make stack-up: wait-for-... scripts run into timeout

### ISSUE THREAD

**Issue by musicEnfanthen** [dasch-swiss/knora-api#1732]
When trying to start the knora-api stack from scratch with `make stack-up` (as described, slightly contradictive, [here](https://docs.dasch.swiss/developers/knora/getting-started/#build-the-docker-image) and [here](https://github.com/dasch-swiss/knora-api/blob/develop/README.md)), I am running into timeout. Docker images are running successfully, but `wait-for-knora.sh` script runs into timeout.

After trying `make init-db-test` and then restarting the stack, now the `wait-for-db.sh` script is timing out.

```
webapi/scripts/wait-for-db.sh
Timed out waiting for DB to start
make: *** [stack-up] Error 1
```

Am I missing something? @benjamingeer @subotic

**Comment by subotic** [comment]
It is necessary to first initialize the DB. The steps would be:

```
$ make init-db-test
$ make stack-up
```

There is a problem with Fuseki, in that it will not start if a lock file is present. You should see it in the logs of the Fuseki container. If this occurs, then you need to run the following:

```
$ make stack-down-delete-volumes
$ make init-db-test
$ make stack-up
```

**Comment by musicEnfanthen** [comment]
Thanks a lot. That did the trick.

The confusion probably derived from the diverging instructions in the docs and the README. The docs say to run `make stack-up` first and then `make init-db-test`. The README actually gives the correct order, but I guess, coming from the doc instructions, I had already "catched" a lock file blocking Fuseki. The `stack-down-delete-volumes` is not mentioned in either place.

Thanks again.

**Comment by subotic** [comment]
No problem.
