### ISSUE TITLE
How to deal with URL citation needs in Salsah 1.5 (and further versions?)

### ISSUE THREAD

**Issue by mrivoal** [dasch-swiss/knora-api#348]
How are we planning to display the URL of resources in the GUI? 

In the previous version of Salsah, it was possible to see the ID of a resource by moving over the resource label with the mouse. I think in Salsal 2.0, the URL of a resource should be displayed somewhere, and I also think that the user should be able to copy-paste it.

It is not a requirement yet, but in the future one of our projects will probably need this functionality in Salsah 1.5.

What do you think about it?

**Comment by loicjaouen** [comment]
outdated by #1313
