### ISSUE TITLE
compile issue: java heap space 

### ISSUE THREAD

**Issue by tobiasschweizer** [dasch-swiss/knora-api#349]
When I tried to run the tests in sbt, I got

> graphdb:testOnly *StandoffUtilSpec*
[info] Compiling 46 Scala sources and 1 Java source to .../Knora_github/webapi/target/scala-2.12/test-classes...
java.lang.OutOfMemoryError: Java heap space

> Java heap space
java.lang.OutOfMemoryError: Java heap space

I could solve the problem using the sbt option: `sbt -J-Xmx2G` (see: <http://stackoverflow.com/questions/15280839/how-to-set-heap-size-for-sbt>)

Do we set additional options for sbt in the configuration for `WebapiBuild.sbt`?

There are already settings there that look ok to me:

```
lazy val javaRunOptions = Seq(
    // "-showversion",
    "-Xms2048m",
    "-Xmx4096m"
    // "-verbose:gc",
    //"-XX:+UseG1GC",
    //"-XX:MaxGCPauseMillis=500"
)

lazy val javaTestOptions = Seq(
    // "-showversion",
    "-Xms2048m",
    "-Xmx4096m"
    // "-verbose:gc",
    //"-XX:+UseG1GC",
    //"-XX:MaxGCPauseMillis=500",
    //"-XX:MaxMetaspaceSize=4096m"
)
```

**Comment by benjamingeer** [comment]
Yes, that sounds OK to me. Does it work if you do that?

**Comment by benjamingeer** [comment]
@subotic, is this correct?

**Comment by subotic** [comment]
Strange. Tests are run with forking enabled. This means that a new JVM is started. That is why we have the ``javaTestOptions`` defined in ``WebapiBuild.sbt``. It shouldn't matter, with how much memory ``sbt`` is started. At least, this is what I thought.

If it works, then it is totally fine :-)

**Comment by subotic** [comment]
Ah, now I see. SBT has problems compiling. Giving it more memory is just fine. Knora is getting big ;-)

**Comment by tobiasschweizer** [comment]
So do we need to launch sbt with more options?

**Comment by subotic** [comment]
I never do. Sometimes it is enough to exit and start ``sbt`` again. Or if you wan't you can add the add the memory flag to ``/usr/local/etc/sbtopts`` so that you don't need to type so much every time you start it.

**Comment by subotic** [comment]
I actually do. I have this set in my ``.bashrc`` / ``.zshrc``:

``export SBT_OPTS="-Xms2048M -Xmx2048M -Xss6M"``

**Comment by SepidehAlassi** [comment]
@subotic this issue is irrelevant now that we are using Bazel, can we close it?

**Comment by subotic** [comment]
yes, thanks.
