### ISSUE TITLE
Why does SALSAH assume that there is a year zero in the Gregorian calendar?

### ISSUE THREAD

**Issue by benjamingeer** [dasch-swiss/knora-api#578]
A comment in `datehelpers.js` says:

```
// Please note the these functions originally asume that the gregorian  calender
// has a year 0. In PHP however, the gregorian year 0 does not exist!
```

This doesn't make sense to me. [There is no year zero in the Gregorian calendar](https://en.wikipedia.org/wiki/Year_zero):

> Year zero does not exist in the Anno Domini system usually used to number years in the Gregorian calendar and in its predecessor, the Julian calendar. In this system, the year 1 BC is followed by AD 1.

The same code comment also says:

```
// adapted from "http://www.fourmilab.ch/documents/calendar/"
```

That web page says:

> While one can't properly speak of “Gregorian dates” prior to the adoption of the calendar in 1582, the calendar can be extrapolated to prior dates. In doing so, this implementation uses the convention that the year prior to year 1 is year 0. This differs from the Julian calendar in which there is no year 0—the year before year 1 in the Julian calendar is year −1.

In the Knora API server, we use the [Jodd](http://jodd.org/doc/jdatetime.html) date conversion library, which assumes that there is no year 0 in the Gregorian calendar.

The decision about whether to include a year 0 affects date searches, because it changes the Julian Day Number that is generated for a given BCE date. For example:

| Date            | Calendar                    | JDN     |
|-----------------|-----------------------------|---------|
| 0001-01-01 BCE | Gregorian with year zero    | 1720695 |
| 0001-01-01 BCE | Gregorian without year zero | 1721060 |
| 0001-01-01 BCE | Julian                      | 1721058 |

If you're comparing 0001-01-01 BCE (Gregorian) with 0001-01-01 BCE (Julian), and you assume there's no Gregorian year 0, they're only 2 days apart. If you assume a Gregorian year 0, they're 363 days apart.

Since there's no year 0 in real Gregorian dates, I think we shouldn't assume a year 0 when converting them to JDN.

Does this make sense, or am I missing something?

**Comment by benjamingeer** [comment]
@SepidehAlassi asked Martin Mattmüller about this, and he said that in his view, it makes no sense to allow Gregorian BC dates, or any Gregorian dates that are earlier than the introduction of the Gregorian calendar in 1582 AD.

Moreover, he thinks that we could also disallow Julian dates earlier than the introduction of the Julian calendar in 45 BC. But in that case, we would need to invent a new, pre-Julian calendar for earlier dates. However, I don't see what such a new calendar could be, except the Julian calendar with another name.

So I suggest we just disallow Gregorian dates before 15 October 1582 AD. Then it doesn't matter what the date libraries do with Gregorian BC dates, because no such dates will occur.

**Comment by loicjaouen** [comment]
That's properly amazing, so the Gregorian calendar is based upon a date (the start of the Anno Domini) that doesn't exist in the calendar.

One could define a calendar as an absolute set of formulas to decide how to call the day corresponding to any moment in time, regardless of historic event.

But one can also accept the definition of *kalendarium*, an account book of historical event (according to my dictionary), where days are named after what was noted at the time. The switch on Gregorian 15th of October 1582 makes that there is no 14th as the 15th was the tomorrow of the Julian 4th of October 1582. Why not, there is no 29th of February in 2018, after all.

Still, that raises a few questions, for example, you say that there is no Julian date before 45 BC, I strongly doubt that there was a historical event where a time accountant wrote such a date as Julian 45 BC (or he was very good at predicting the Anno Domini).

And if we accept the "account book of historical event", we need much more calendars, like the Russian Julian Calendar to record dates there until 1918. And it is true that that calendar exists and for sure a Tsar historian will want to use it.

But we also need an absolute and non historical calendar, that we, unfortunately, historically got used to call "Gregorian".

**Comment by benjamingeer** [comment]
> One could define a calendar as an absolute set of formulas to decide how to call the day corresponding to any moment in time, regardless of historical events.

One could, but historians haven't done this, and I think it's not our job to do it. People who study Islamic history use the Islamic calendar, because that's what's used in their sources, and it gets tricky to convert dates all the time, especially imprecise ones. No doubt specialists in Chinese history use the Chinese calendar.

> Still, that raises a few questions, for example, you say that there is no Julian date before 45 BC, I strongly doubt that there was a historical event where a time accountant wrote such a date as Julian 45 BC (or he was very good at predicting the Anno Domini).

At that time, years were numbered differently, with year 1 being the first year of the reign of the current Roman consul. The Julian calendar reform of 45 BC didn't affect that. The Anno Domini system was of course added later.

> But we also need an absolute and non historical calendar, that we, unfortunately, historically got used to call "Gregorian".

If you extrapolate the Gregorian calendar back before 1582, it's called the [proleptic Gregorian calendar](https://en.wikipedia.org/wiki/Proleptic_Gregorian_calendar).

You can also do the same thing with the Julian calendar, which is then called the [proleptic Julian calendar](https://en.wikipedia.org/wiki/Proleptic_Julian_calendar).

Wikipedia points out that the adoption of the Gregorian calendar was uneven: "Great Britain and its possessions were using the Julian calendar until September 1752."

The proleptic Gregorian calendar has the problem that nobody seems to agree on whether there is a year 0. Wikipedia says:

> For these calendars one can distinguish two systems of numbering years BC. Bede and later historians did not use the Latin zero, nulla, as a year (see 0 (year)), so the year preceding AD 1 is 1 BC. In this system the year 1 BC is a leap year (likewise in the proleptic Julian calendar). Mathematically, it is more convenient to include a year 0 and represent earlier years as negative, for the specific purpose of facilitating the calculation of the number of years between a negative (BC) year and a positive (AD) year. This is the convention used in astronomical year numbering and in the international standard date system, ISO 8601. In these systems, the year 0 is a leap year.

So I think the problem is that if you use the proleptic Gregorian calendar, you introduce ambiguity and potential errors because of conflicting assumptions about year 0, as I wrote in the description of this issue.

On the other hand, the proleptic Julian calendar is not straightforward either:

> The determination of leap years in the proleptic Julian calendar (in either numbering) is distinct from the question of which years were historically considered leap years during the Roman era, due to the leap year error: Between 45 BC and AD 4, the leap day was somewhat unsystematic. Thus there is no simple way to find an equivalent in the proleptic Julian calendar of a date quoted using the Roman pre-Julian calendar (AUC or by reference to consuls).

And there are still more complexities, because the new year started on 25 March in much of medieval and early modern Europe, and was only gradually replaced by 1 January. This caused confusion even at the time:

http://www.cree.name/genuki/dates.htm

So now I am less certain than ever about what Knora should do.
