### ISSUE TITLE
http://0.0.0.0:3333 routes never return

### ISSUE THREAD

**Issue by gfoo** [dasch-swiss/knora-api#938]
hello,
I've a strange issue with routes http://0.0.0.0:3333/v2, it never return while it works with http://**localhost**:3333/v2 ?
Until today it was working, but I was on vacations last two weeks, so I only updated Knora (dev branch) today and now I've this issue.

**Comment by loicjaouen** [comment]
`0.0.0.0` is normally used as a wild card to mean "whatever ip on this network stack".

knora config says to listen on `0.0.0.0:3333` so it works wether you use localhost (127.0.0.1) or an assigned ip (dchp, config):
https://github.com/dhlab-basel/Knora/blob/bc5043c4d88770993c686093102c6052b8b30579/webapi/src/main/resources/application.conf#L281

So as it is, it should work.

**Comment by loicjaouen** [comment]
Still, my assumption is that putting `0.0.0.0:3333`, on mac at least, the OS doesn't detect port collision if another app is using `3333`.

There is a strange that I mentioned here: https://stackoverflow.com/questions/27269277/cant-find-which-process-is-listening-on-port-8001-on-mac-os-x/49051200#49051200

So try to shut down our VPN that is eager to listen to 3333.

And let me know because, I often have to reboot as it doesn't want to free the port.

**Comment by loicjaouen** [comment]
yes, `lsof` shows:

```
PulseSetu 2701 gfaucher    5u  IPv4 0x6d3f6bbcc42dd23b      0t0  TCP 127.0.0.1:3333 (LISTEN)
PulseSetu 2701 gfaucher    6u  IPv4 0x6d3f6bbcbb61cf7b      0t0  TCP 127.0.0.1:3333->127.0.0.1:49637 (ESTABLISHED)
Postman   5256 gfaucher   96u  IPv4 0x6d3f6bbca824acbb      0t0  TCP 127.0.0.1:49637->127.0.0.1:3333 (ESTABLISHED)
java      5392 gfaucher  289u  IPv6 0x6d3f6bbcb80575d3      0t0  TCP *:3333 (LISTEN)
```

PulseSecure listens to `127.0.0.1:3333`, knora listens to `*:3333`, the port collision was not detected and knora had no `port already used` error showing up.

Still, when postman makes a request to `0.0.0.0:3333`, it gets connected to PulseSecure at `127.0.0.1:3333`.

**Comment by loicjaouen** [comment]
@subotic : maybe the default adress for knora should not be `0.0.0.0`?

then the gravsearch examples should be updated ( https://docs.knora.org/paradox/03-apis/api-v2/query-language.html )

**Comment by gfoo** [comment]
exactly, Pulse secure causes the collision. thx

**Comment by subotic** [comment]
We need to use `0.0.0.0` because of CORS. One could of course use the IP address of the computer.
