### ISSUE TITLE
Deleting ontologies using API v2

### ISSUE THREAD

**Issue by lrosenth** [dasch-swiss/knora-api#974]
Using the API I can not delete an ontology.
To test, run the attached PHP script 2 times. Second time it failed with an error

[ontoldeltest.php.zip](https://github.com/dhlab-basel/Knora/files/2310967/ontoldeltest.php.zip)

**Comment by kilchenmann** [comment]
I was able to delete an ontology using the API. This works well, but the cache (`CacheUtil`?) does not update the change. The documentation says, that "the ontology cache is updated only when the ontology responder processes a request to update an ontology.", but not on delete an ontology?

**Comment by benjamingeer** [comment]
@lrosenth I'm sorry I seem to have completely overlooked this issue. When I run your script twice, I get this result:

```
% php ontoldeltest.php 
GET http://0.0.0.0:3333/admin/projects/http://rdfh.ch/projects/1011
JSON ERROR CODE = 4
RESULT = The requested resource could not be found.
POST http://0.0.0.0:3333/admin/projects
-->project IRI: http://rdfh.ch/projects/1011
GET http://0.0.0.0:3333/v2/ontologies/metadata/http://rdfh.ch/projects/1011
POST http://0.0.0.0:3333/v2/ontologies
benjamingeer@euler Desktop % php ontoldeltest.php
GET http://0.0.0.0:3333/admin/projects/http://rdfh.ch/projects/1011
JSON ERROR CODE = 4
RESULT = The requested resource could not be found.
POST http://0.0.0.0:3333/admin/projects
ERROR in "knora API" at line: 186
org.knora.webapi.DuplicateValueException: Project with the shortname: 'GAGA' already exists
```

It seems that the issue is that you are trying to create a project with the same name twice. This doesn't seem to have anything to do with deleting an ontology.

@kilchenmann Knora already has an automated test for this, and it seems to be working fine. Are you sure the ontology isn't being cached by the client?

**Comment by kilchenmann** [comment]
> Knora already has an automated test for this, and it seems to be working fine. 

I thought so.

> Are you sure the ontology isn't being cached by the client?

After deleting the ontology I was getting the response:

```json
{
  "knora-api:result" : "Ontology http://0.0.0.0:3333/ontology/1234/notizblogg/v2 has been deleted",
  "@context" : {
    "knora-api" : "http://api.knora.org/ontology/knora-api/v2#"
  }
}
```

But after requesting the ontology or the list of all ontologies on the API directly, with various browsers and postman, the ontology is still there. The only thing that helped was a restart of the api.

**Comment by benjamingeer** [comment]
You're right, there's a bug in the test, too. :) Will fix, thanks!
